<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
	</head>
	<body>
		<script>
			function takeLongTime(n) {
				return new Promise(resolve => {
					setTimeout(() => resolve(n + 200), n);
				});
			}

			function step1(n) {
				console.log(`step1 with ${n}`);
				return takeLongTime(n);
			}

			function step2(n) {
				console.log(`step2 with ${n}`);
				return takeLongTime(n);
			}

			function step3(n) {
				console.log(`step3 with ${n}`);
				return takeLongTime(n);
			}
			// let value1 = step1(1000).then(value1 => {
			// 	console.log('1', value1);
			// 	return value1;
			// });
			// let value2 = step2(value1).then(value2 => {
			// 	console.log('2', value2);
			// 	return value2;
			// });
			// step3(value2).then(value3 => {
			// 	console.log('3', value3);
			// });
		</script>
		<script>
			function doIt() {
				console.time("doIt");
				const time1 = 300;
				step1(time1)
					.then(time2 => step2(time2))
					.then(time3 => step3(time3))
					.then(result => {
						console.log(`result is ${result}`);
						console.timeEnd("doIt");
					});
			}
			// doIt();
		</script>
		<script>
			async function doIt1() {
				console.time("doIt");
				const time1 = 300;
				const time2 = await step1(time1);
				const time3 = await step2(time2);
				const result = await step3(time3);
				console.log(`result is ${result}`);
				console.timeEnd("doIt");
			}
			// doIt1();
		</script>
		<script>
			async function fn() {
			    try {
			        let a = await Promise.reject('error')
			    } catch(error) {
			        console.log(error)
			    }
			}
			fn(); // error
		</script>
	</body>
</html>
